{
 "title": "HiveMQ Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System CPU Used %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "cpu.total - $tag_node",
     "expr": "com_hivemq_system_os_global_cpu_total_total",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} cpu.total",
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") + mean(\"usage_guest\")  + mean(\"usage_guest_nice\") + mean(\"usage_iowait\") + mean(\"usage_irq\") + mean(\"usage_nice\") + mean(\"usage_softirq\") + mean(\"usage_steal\") + mean(\"usage_system\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Memory Used %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "mem.total - $tag_node",
     "expr": "com_hivemq_system_os_global_memory_total - com_hivemq_system_os_global_memory_available",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} mem.used",
     "measurement": "mem",
     "query": "SELECT mean(\"usage_user\") + mean(\"usage_guest\")  + mean(\"usage_guest_nice\") + mean(\"usage_iowait\") + mean(\"usage_irq\") + mean(\"usage_nice\") + mean(\"usage_softirq\") + mean(\"usage_steal\") + mean(\"usage_system\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval), \"node\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "com_hivemq_system_os_global_memory_total",
     "legendFormat": "{{instance}} mem.total"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hivemq_system_os_process_memory_resident_set_size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} memory-resident",
     "measurement": "com.hivemq.system.os.process.memory.resident-set-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "com_hivemq_jvm_memory_heap_max", "legendFormat": "{{instance}} heap.max" },
    {
     "expr": "com_hivemq_jvm_memory_heap_init",
     "legendFormat": "{{instance}} heap.init"
    },
    {
     "expr": "com_hivemq_jvm_memory_heap_used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} heap.used",
     "measurement": "com.hivemq.jvm.memory.heap.used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT packets (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "mqtt.incoming - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_total_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} messages.incoming",
     "measurement": "com.hivemq.messages.incoming.total.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "mqtt.outgoing - $tag_host",
     "expr": "delta(com_hivemq_messages_outgoing_total_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} messages.outgoing",
     "measurement": "com.hivemq.messages.outgoing.total.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retained Messages (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "retained-messages - $tag_host",
     "expr": "com_hivemq_messages_retained_current",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} retained-messages",
     "measurement": "com.hivemq.messages.retained.current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_cluster_nodes_count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} Cluster nodes",
     "measurement": "com.hivemq.cluster.nodes.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT Sessions (1m, stacked)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "MQTT Sessions - $tag_host",
     "expr": "com_hivemq_sessions_overall_current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} MQTT Sessions",
     "measurement": "com.hivemq.sessions.overall.current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PING outgoing (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ping.outgoing - $tag_host",
     "expr": "delta(com_hivemq_messages_outgoing_pingresp_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} ping.outgoing",
     "measurement": "com.hivemq.messages.outgoing.pingresp.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PING incoming (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ping.incoming - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_pingreq_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} ping.incoming",
     "measurement": "com.hivemq.messages.incoming.pingreq.count",
     "query": "increase(metrics_com_hivemq_messages_incoming_total_count_count)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Connections (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "connections - $tag_host",
     "expr": "com_hivemq_networking_connections_current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} connections",
     "measurement": "com.hivemq.networking.connections.current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CONNECT (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "connect.rate - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_connect_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} connect.rate",
     "measurement": "com.hivemq.messages.incoming.connect.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Closed Connections (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "closed_connections.rate - $tag_host",
     "expr": "delta(com_hivemq_networking_connections_closed_total_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} closed_connections.rate",
     "measurement": "com.hivemq.networking.connections-closed.total.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Subscriptions (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "subscribe.count - $tag_host",
     "expr": "com_hivemq_subscriptions_overall_current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} subscribe.count",
     "measurement": "com.hivemq.subscriptions.overall.current",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SUBSCRIBE (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "subscribe.rate - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_subscribe_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} ",
     "measurement": "com.hivemq.messages.incoming.subscribe.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUBLISH incoming (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "publish.incoming - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_publish_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} publish.incoming",
     "measurement": "com.hivemq.messages.incoming.publish.count",
     "query": "increase(metrics_com_hivemq_messages_incoming_total_count_count)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUBLISH outgoing (stacked, 1m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "publish.outgoing - $tag_host",
     "expr": "delta(com_hivemq_messages_outgoing_publish_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} publish.outgoing",
     "measurement": "com.hivemq.messages.outgoing.publish.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Bytes Outgoing (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Network Bytes Sent - $tag_node",
     "expr": "delta(com_hivemq_system_os_network_interface_eth0_bytes_sent[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Network Bytes Sent",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Bytes Incoming (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Network Bytes Received - $tag_node",
     "expr": "delta(com_hivemq_system_os_network_interface_eth0_bytes_received[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Network Bytes Received",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dropped Messages by Reason (1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "inflight-window-full - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_message_too_large_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} message-too-large",
     "measurement": "com.hivemq.messages.dropped.in-flight-window.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "internal-error - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_not_writable_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} not-writable",
     "measurement": "com.hivemq.messages.dropped.internal-error.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "not-connected - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_qos_0_memory_exceeded_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} qos0-memory-exceeded",
     "measurement": "com.hivemq.messages.dropped.not-connected.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "not-writeable - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_queue_full_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} queue-full",
     "measurement": "com.hivemq.messages.dropped.not-writable.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "qos0-queue-not-empty - $tag_host",
     "expr": "delta(com_hivemq_messages_dropped_internal_error_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} internal-error",
     "measurement": "com.hivemq.messages.dropped.qos-0-queue-not-empty.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage Collections Young Gen  (1m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "GC M&S - $tag_host",
     "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Young_Generation_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} GC M&S",
     "measurement": "com.hivemq.jvm.garbage-collector.G1-Young-Generation.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage Old Gen (1m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "GC Old Gen - $tag_host",
     "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Old_Generation_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} GC Old Gen",
     "measurement": "com.hivemq.jvm.garbage-collector.G1-Old-Generation.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage Collections Times (1m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "GC Young Time - $tag_host",
     "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Young_Generation_time[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} GC Young Time",
     "measurement": "com.hivemq.jvm.garbage-collector.G1-Young-Generation.time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "GC Old Time - $tag_host",
     "expr": "delta(com_hivemq_jvm_garbage_collector_G1_Old_Generation_time[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} GC Old Time",
     "measurement": "com.hivemq.jvm.garbage-collector.G1-Old-Generation.time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Bytes Read/Write (1m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Disk Bytes Read - $tag_node",
     "expr": "delta(com_hivemq_system_os_disks__dev_vda_read_bytes[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Disk Bytes Read",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Disk Bytes Write - $tag_node",
     "expr": "delta(com_hivemq_system_os_disks__dev_vda_write_bytes[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Disk Bytes Write",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UNSUBSCRIBE (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "unsubscribe.rate - $tag_host",
     "expr": "delta(com_hivemq_messages_incoming_unsubscribe_count[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} unsubscribe.rate",
     "measurement": "com.hivemq.messages.incoming.unsubscribe.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Protection Level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Overload Protection level - $tag_host",
     "expr": "com_hivemq_overload_protection_level",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} Overload Protection level",
     "measurement": "com.hivemq.overload-protection.level",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Protection avg Credits (1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hivemq_overload_protection_clients_average_credits",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Average Credits",
     "measurement": "com.hivemq.overload-protection.clients.average-credits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Protection Credits per tick (10s)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "com_hivemq_overload_protection_credits_per_tick",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "com.hivemq.overload-protection.credits.per-tick",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Protection Backpressure (stacked, max, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Active backpressure - $tag_host",
     "expr": "com_hivemq_overload_protection_clients_backpressure_active",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} Active backpressure",
     "measurement": "com.hivemq.overload-protection.clients.backpressure-active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Protection Using Credits (stacked, 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Using Credits - $tag_host",
     "expr": "com_hivemq_overload_protection_clients_using_credits",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}} Using Credits",
     "measurement": "com.hivemq.overload-protection.clients.using-credits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}